### ISSUE TITLE
changing language code from "ckb" to "ku"

### ISSUE THREAD

**Issue by Ahmedalanee** [mustafa96m/flutter_ckb_localization#2]
I see it's better to change the language code from "**ckb**" to "**ku**" to be compatible with other software, packages …etc.

**Comment by su0f** [comment]
Hey @Ahmedalanee!

the "CKB" abbreviation was chosen based on [ISO-369-3](https://en.wikipedia.org/wiki/ISO_639-3) to be consistent with the official flutter localization library naming convention. 

Although, feel free to fork and change the language code if you prefer something else.

Thanks for reaching out.
